apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-logging
  namespace: kube-system
spec:
  interval: 10m
  dependsOn:
    - name: rancher-logging-crd
  chart:
    spec:
      chart: rancher-logging
      version: '105.2.1+up4.10.0'
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: kube-system
      interval: 10m
  targetNamespace: cattle-logging-system
  values:
    additionalLoggingSources:
      rke2:
        enabled: true
    debug: true
    disablePvc: true
    logging:
      enabled: true
      fluentd:
        dnsConfig:
          nameservers:
          - 169.254.20.10
          options:
          - name: ndots
            value: "1"
          - name: timeout
            value: "2"
          - name: attempts
            value: "5"
          - name: edns0
          searches: []
    fluentbit:
      dnsConfig:
        nameservers:
        - 169.254.20.10
        options:
        - name: ndots
          value: "1"
        - name: timeout
          value: "2"
        - name: attempts
          value: "5"
        - name: edns0
        searches: []
      resources:
        requests:
          cpu: 10m
          memory: 512Mi
    fluentd:
      dnsConfig:
        nameservers:
        - 169.254.20.10
        options:
        - name: ndots
          value: "1"
        - name: timeout
          value: "2"
        - name: attempts
          value: "5"
        - name: edns0
        searches: []
      replicas: 1
      resources:
        requests:
          cpu: 20m
          memory: 512Mi
    global:
      seLinux:
        enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
