apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-logging-crd
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: rancher-logging-crd
      version: '105.2.1+up4.10.0'
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: kube-system
      interval: 10m
  targetNamespace: cattle-logging-system
